### ISSUE TITLE
Remove 'Share your passport as an electronique format.' when I got passports

### ISSUE THREAD

**Issue by qcastel** [idhub-io/idhub-app#3]
You can remove the 'Share your passport as an electronique format.' part when you got a passport already.

Btw the button 'Generate your digital passports' doesn't work

**Comment by qcastel** [comment]
![Uploading Screenshot 2020-12-01 at 11.18.51.png…]()

**Comment by qcastel** [comment]
![Screenshot 2020-12-01 at 11 18 51](https://user-images.githubusercontent.com/3748231/100734357-72a73000-33c7-11eb-958f-9425403fbda4.png)

**Comment by shprink** [comment]
tu as une vielle version. Ca le fait plus et il y a une superbe animations :P

**Comment by shprink** [comment]
reouvre si ca marche pas
