### ISSUE TITLE
Github logo not dark friendly

### ISSUE THREAD

**Issue by qcastel** [idhub-io/idhub-app#4]
![Screenshot 2020-12-01 at 11 25 07](https://user-images.githubusercontent.com/3748231/100734634-e0535c00-33c7-11eb-96b1-e9f209edf604.png)

**Comment by shprink** [comment]
ouai il faut que j'ai une facon dans le JS de savoir si on est en dark mode ou pas. ca aidera aussi pour generer le qrcode dark

**Comment by qcastel** [comment]
https://ionicframework.com/docs/theming/dark-mode

```
const prefersDark = window.matchMedia('(prefers-color-scheme: dark)');
```

**Comment by qcastel** [comment]
Fixed
