### ISSUE TITLE
Overlap of views

### ISSUE THREAD

**Issue by qcastel** [idhub-io/idhub-app#6]
Seems the previous view is still behind it, which cause the double cross.

![Screenshot 2020-12-01 at 11 28 13](https://user-images.githubusercontent.com/3748231/100734924-535cd280-33c8-11eb-942c-e387e8428ba5.png)

**Comment by shprink** [comment]
ouai j'ai taffé exclusivement sur ios la. le default web c'est android. faut que je ragarde

**Comment by qcastel** [comment]
<img width="612" alt="Screenshot 2020-12-01 at 13 35 07" src="https://user-images.githubusercontent.com/3748231/100747510-0eda3280-33da-11eb-92ce-69c45eb9d4e0.png">
another example.
Perhaps just a background to the front view would avoid seeing this?

**Comment by shprink** [comment]
j'ai forcé ios + background opacity a 0.9 plutot que 0.7
